### PR TITLE
Generate artifacts and prereleases in CI

### PR DESCRIPTION
**Pull request by mgree**
We can have CI generate the manpage, which should simplify #61 and #64.

### CODE REVIEW

**Comment by mgree** [comment]
@gliargovas @angelhof @ericzty NB some changes to the CI to drop `exit_code.sh` and have `run_tests.sh` return an appropriate exit code.

**Comment by mgree** [comment]
Also... why do we need to do the `cd`/`cp -R` song and dance?

**Comment by angelhof** [comment]
> Also... why do we need to do the `cd`/`cp -R` song and dance?

If I recall correctly it was added to avoid issues with ownership of some directories. @ericzty is that right or do I misremember?

**Review by angelhof — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
