### PR TITLE
Minor codestyle improvements

### PR DESCRIPTION
**Pull request by a1346054**

### CODE REVIEW

**Review by angelhof — APPROVED** [review]
Looks good to me, thank you very much! Let's wait for @mgree to review too before merging.

**Comment by mgree** [comment]
I'm not super happy with the `bash` dependency in our tests, and this makes it worse. It also adds a bunch of things to tests that don't really make sense to me---e.g., in the touch and rm test, it adds effects in other files. That's a good new test, but that's also a different PR than "codestyle improvements".

I appreciate the doc improvements, though! Can we cherry-pick those into a separate PR?

Whitespace fixes aren't much help without CI to enforce them. I'd be happy to take a PR that did both, but cleaning up whitespace without enforcing it just means we'll need to clean it up again later.

**Comment by a1346054** [comment]
Feel free to cherry-pick any commits you like and consider ready.

I'll think about how I'd go about removing bash dependency from tests and rewriting it for posix-compliant shells.

**Comment by mgree** [comment]
Obsoleted by #109. Thank you, @a1346054, for these commits!

**Pull request closed without merging**
